### ISSUE TITLE
Latest version of Perl don't work

### ISSUE THREAD

**Issue by bdenison99** [Microsoft/StorScore#34]
Many variations of:
"Experimental keys on scalar is now forbidden at C:\StorScore\parse_results.cmd line 1385."

**Comment by marksantaniello** [comment]
Yeah, you're not the first person to report this.  The fix is pretty simple: you have to change “keys $foo” to “keys %$foo” wherever that occurs.  If you want to submit a PR we will think you are super awesome :)

Otherwise if you just keep using Active Perl 5, version 18, subversion 2 (or the equivalent Strawberry Perl) it should be OK.

**Comment by bdenison99** [comment]
It was a little more complicated than that - had to wrap { } around the stuff that % applies to.  I think I've created a pull request correctly - hope it helps.
