### ISSUE TITLE
4k_RR Recipe inconsistency 

### ISSUE THREAD

**Issue by jetOak** [Microsoft/StorScore#38]
I've been running the 4k_RR StorScore recipe on various drives and I have came across this issue:

![results_image](https://cloud.githubusercontent.com/assets/17860945/19978442/2c9275ec-a1b4-11e6-84e4-620a09f00b34.PNG)

For most drives that I have tested the test description reads "4K_Random_Reads-step-4" however for a few other drives the test description reads as "4K_Random_Reads-step-2".  I selected the 4K_RR recipe each time.  Is there a reason for this inconsistency?

![2s](https://cloud.githubusercontent.com/assets/17860945/19979857/31849f6c-a1b9-11e6-9cb7-5f225cf835a8.png)

![4s](https://cloud.githubusercontent.com/assets/17860945/19979858/3451ba72-a1b9-11e6-9437-d7c8c4e2262e.png)

**Comment by marksantaniello** [comment]
We have auto-detect logic for HDD vs SSD.  In the former case, we don't bother preconditioning since it has little value.  The output (just prior to your screen shots) should include the result of our auto-detection.  If it fails for some reason, you can always override it on the command line with --target_type=ssd|hdd

**Comment by jetOak** [comment]
Both of these tests were performed on SATA SSDs.  Is there a reason why the program would detect an SSD as an HDD?

**Comment by marksantaniello** [comment]
It's been a while, but what I recall is that there is a standard field in the response to the SATA IDENTIFY command that states something about the "rotation rate" or "rotational latency" of the (presumed) HDD.  Once SSDs appeared on the scene, the standard was amended to say something like, "SSDs should just return 1 for this field" or similar.

So that's the underlying mechanism.  

If you have some kind of weird SAS adapter in the middle, or maybe you've got all the devices behind a RAID card, or a hybrid device which is neither pure SSD or HDD, or some strange driver, or broken SSD firmware -- any number of reasons -- the response might be incorrect.

So we announce the result of the auto-detection and provide --target_type to override in case it's wrong.  The alternative was to require --target_type all the time, which is annoying, since usually we get it right.

**Comment by jetOak** [comment]
Your suggestion fixed the issue.  Thank you for the information and the assistance.

**Comment by lauracaulfield** [comment]
For the interested reader -- here is the logic for determining whether the drive is SSD or HDD: https://github.com/Microsoft/StorScore/blob/master/lib/Target.pm#L173
